//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeOS.Hub.Tools.UpdateManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetupWorkingDirUserSelectedPath {
            get {
                return ((string)(this["SetupWorkingDirUserSelectedPath"]));
            }
            set {
                this["SetupWorkingDirUserSelectedPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Secure FTP Repository Name")]
        public string SetupRepoAcctInfo {
            get {
                return ((string)(this["SetupRepoAcctInfo"]));
            }
            set {
                this["SetupRepoAcctInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[format = ftp://yourserver.com]")]
        public string SetupRepoAccountHost {
            get {
                return ((string)(this["SetupRepoAccountHost"]));
            }
            set {
                this["SetupRepoAccountHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetupRepoAccountPort {
            get {
                return ((string)(this["SetupRepoAccountPort"]));
            }
            set {
                this["SetupRepoAccountPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp login")]
        public string SetupRepoAccountLogin {
            get {
                return ((string)(this["SetupRepoAccountLogin"]));
            }
            set {
                this["SetupRepoAccountLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp login pw")]
        public string SetupRepoAccountPassword {
            get {
                return ((string)(this["SetupRepoAccountPassword"]));
            }
            set {
                this["SetupRepoAccountPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("storage account name")]
        public string SetupAzureAccountName {
            get {
                return ((string)(this["SetupAzureAccountName"]));
            }
            set {
                this["SetupAzureAccountName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("storage account key")]
        public string SetupAzureAccountKey {
            get {
                return ((string)(this["SetupAzureAccountKey"]));
            }
            set {
                this["SetupAzureAccountKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azure Storage Account Title")]
        public string SetupAzureAccountTitle {
            get {
                return ((string)(this["SetupAzureAccountTitle"]));
            }
            set {
                this["SetupAzureAccountTitle"] = value;
            }
        }
    }
}
